/********************************************************************************
** Form generated from reading UI file 'mqs_surface_settings.ui'
**
** Created by: Qt User Interface Compiler version 5.0.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MQS_SURFACE_SETTINGS_H
#define UI_MQS_SURFACE_SETTINGS_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_SurfaceSetting
{
public:
    QTabWidget *tabWidget;
    QWidget *Color;
    QGroupBox *groupBox;
    QLabel *label_5;
    QSlider *horizontalSlider_Brightness;
    QSlider *horizontalSlider_Contrast;
    QLabel *label_6;
    QSlider *horizontalSlider_Transparency;
    QLabel *label_7;
    QSlider *horizontalSlider_R;
    QLabel *label_31;
    QLabel *label_32;
    QSlider *horizontalSlider_G;
    QSlider *horizontalSlider_B;
    QLabel *label_33;
    QSpinBox *spinBox_Brightness;
    QSpinBox *spinBox_Contrast;
    QSpinBox *spinBox_Transparency;
    QSpinBox *spinBox_R;
    QSpinBox *spinBox_B;
    QSpinBox *spinBox_G;
    QGroupBox *groupBox_3;
    QSlider *horizontalSlider_chroma_R;
    QLabel *label_43;
    QLabel *label_44;
    QSlider *horizontalSlider_chroma_G;
    QSlider *horizontalSlider_chroma_B;
    QLabel *label_45;
    QSpinBox *spinBox_chroma_R;
    QSpinBox *spinBox_chroma_G;
    QSpinBox *spinBox_chroma_B;
    QSpinBox *spinBox_chroma_RT;
    QLabel *label_46;
    QSlider *horizontalSlider_chroma_GT;
    QLabel *label_47;
    QSlider *horizontalSlider_chroma_RT;
    QLabel *label_48;
    QSlider *horizontalSlider_chroma_BT;
    QSpinBox *spinBox_chroma_BT;
    QSpinBox *spinBox_chroma_GT;
    QPushButton *button_pick_color;
    QCheckBox *checkBoxChromaEnabled;
    QWidget *Possition;
    QGroupBox *Position;
    QLabel *label;
    QSlider *horizontalSlider_X_Pos;
    QLabel *label_2;
    QSlider *horizontalSlider_Width;
    QLabel *label_3;
    QSlider *horizontalSlider_Y_Pos;
    QLabel *label_4;
    QSlider *horizontalSlider_Height;
    QSpinBox *spinBox_X_Pos;
    QSpinBox *spinBox_Width;
    QSpinBox *spinBox_Y_Pos;
    QSpinBox *spinBox_Height;
    QCheckBox *checkBox_keepaspect;
    QGroupBox *Position_3;
    QLabel *label_9;
    QSlider *horizontalSlider_X_Angle;
    QLabel *label_10;
    QSlider *horizontalSlider_Y_Angle;
    QLabel *label_11;
    QSlider *horizontalSlider_Z_Angle;
    QLabel *label_12;
    QSlider *horizontalSlider_Animate;
    QSpinBox *spinBox_X_Angle;
    QSpinBox *spinBox_Y_Angle;
    QSpinBox *spinBox_Animate;
    QSpinBox *spinBox_Z_Angle;
    QGroupBox *Position_4;
    QLabel *label_13;
    QSlider *horizontalSlider_Clip_Top;
    QLabel *label_14;
    QSlider *horizontalSlider_Clip_Left;
    QLabel *label_15;
    QSlider *horizontalSlider_Clip_Bottom;
    QLabel *label_16;
    QSlider *horizontalSlider_Clip_Right;
    QSpinBox *spinBox_Clip_Top;
    QSpinBox *spinBox_Clip_Left;
    QSpinBox *spinBox_Clip_Bottom;
    QSpinBox *spinBox_Clip_Right;
    QWidget *Filters;

    void setupUi(QWidget *SurfaceSetting)
    {
        if (SurfaceSetting->objectName().isEmpty())
            SurfaceSetting->setObjectName(QStringLiteral("SurfaceSetting"));
        SurfaceSetting->setWindowModality(Qt::ApplicationModal);
        SurfaceSetting->resize(440, 325);
        SurfaceSetting->setMinimumSize(QSize(440, 325));
        SurfaceSetting->setMaximumSize(QSize(440, 325));
        QIcon icon;
        icon.addFile(QStringLiteral(":/MediaQuickSync/resources/GoContactSyncLogo.ico"), QSize(), QIcon::Normal, QIcon::Off);
        SurfaceSetting->setWindowIcon(icon);
        tabWidget = new QTabWidget(SurfaceSetting);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(0, 2, 439, 323));
        Color = new QWidget();
        Color->setObjectName(QStringLiteral("Color"));
        groupBox = new QGroupBox(Color);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(2, 0, 429, 105));
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(8, 16, 75, 20));
        horizontalSlider_Brightness = new QSlider(groupBox);
        horizontalSlider_Brightness->setObjectName(QStringLiteral("horizontalSlider_Brightness"));
        horizontalSlider_Brightness->setGeometry(QRect(96, 20, 102, 16));
        horizontalSlider_Brightness->setMaximum(100);
        horizontalSlider_Brightness->setOrientation(Qt::Horizontal);
        horizontalSlider_Contrast = new QSlider(groupBox);
        horizontalSlider_Contrast->setObjectName(QStringLiteral("horizontalSlider_Contrast"));
        horizontalSlider_Contrast->setGeometry(QRect(96, 48, 102, 16));
        horizontalSlider_Contrast->setMaximum(100);
        horizontalSlider_Contrast->setOrientation(Qt::Horizontal);
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(8, 44, 63, 20));
        horizontalSlider_Transparency = new QSlider(groupBox);
        horizontalSlider_Transparency->setObjectName(QStringLiteral("horizontalSlider_Transparency"));
        horizontalSlider_Transparency->setGeometry(QRect(96, 78, 102, 16));
        horizontalSlider_Transparency->setMaximum(100);
        horizontalSlider_Transparency->setOrientation(Qt::Horizontal);
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(8, 74, 85, 20));
        horizontalSlider_R = new QSlider(groupBox);
        horizontalSlider_R->setObjectName(QStringLiteral("horizontalSlider_R"));
        horizontalSlider_R->setGeometry(QRect(270, 20, 102, 16));
        horizontalSlider_R->setMaximum(255);
        horizontalSlider_R->setOrientation(Qt::Horizontal);
        label_31 = new QLabel(groupBox);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(252, 16, 16, 20));
        label_32 = new QLabel(groupBox);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(252, 44, 16, 20));
        horizontalSlider_G = new QSlider(groupBox);
        horizontalSlider_G->setObjectName(QStringLiteral("horizontalSlider_G"));
        horizontalSlider_G->setGeometry(QRect(270, 48, 102, 16));
        horizontalSlider_G->setMaximum(255);
        horizontalSlider_G->setOrientation(Qt::Horizontal);
        horizontalSlider_B = new QSlider(groupBox);
        horizontalSlider_B->setObjectName(QStringLiteral("horizontalSlider_B"));
        horizontalSlider_B->setGeometry(QRect(270, 76, 102, 16));
        horizontalSlider_B->setMaximum(255);
        horizontalSlider_B->setOrientation(Qt::Horizontal);
        label_33 = new QLabel(groupBox);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(252, 72, 16, 20));
        spinBox_Brightness = new QSpinBox(groupBox);
        spinBox_Brightness->setObjectName(QStringLiteral("spinBox_Brightness"));
        spinBox_Brightness->setGeometry(QRect(200, 16, 46, 22));
        spinBox_Brightness->setMaximum(100);
        spinBox_Contrast = new QSpinBox(groupBox);
        spinBox_Contrast->setObjectName(QStringLiteral("spinBox_Contrast"));
        spinBox_Contrast->setGeometry(QRect(200, 44, 46, 22));
        spinBox_Contrast->setMaximum(100);
        spinBox_Transparency = new QSpinBox(groupBox);
        spinBox_Transparency->setObjectName(QStringLiteral("spinBox_Transparency"));
        spinBox_Transparency->setGeometry(QRect(200, 72, 46, 22));
        spinBox_Transparency->setMaximum(100);
        spinBox_R = new QSpinBox(groupBox);
        spinBox_R->setObjectName(QStringLiteral("spinBox_R"));
        spinBox_R->setGeometry(QRect(374, 16, 46, 22));
        spinBox_R->setMaximum(256);
        spinBox_B = new QSpinBox(groupBox);
        spinBox_B->setObjectName(QStringLiteral("spinBox_B"));
        spinBox_B->setGeometry(QRect(374, 72, 46, 22));
        spinBox_B->setMaximum(255);
        spinBox_G = new QSpinBox(groupBox);
        spinBox_G->setObjectName(QStringLiteral("spinBox_G"));
        spinBox_G->setGeometry(QRect(374, 44, 46, 22));
        spinBox_G->setMaximum(255);
        groupBox_3 = new QGroupBox(Color);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(2, 132, 429, 105));
        horizontalSlider_chroma_R = new QSlider(groupBox_3);
        horizontalSlider_chroma_R->setObjectName(QStringLiteral("horizontalSlider_chroma_R"));
        horizontalSlider_chroma_R->setGeometry(QRect(26, 20, 102, 16));
        horizontalSlider_chroma_R->setMaximum(255);
        horizontalSlider_chroma_R->setOrientation(Qt::Horizontal);
        label_43 = new QLabel(groupBox_3);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(8, 16, 16, 20));
        label_44 = new QLabel(groupBox_3);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(8, 44, 16, 20));
        horizontalSlider_chroma_G = new QSlider(groupBox_3);
        horizontalSlider_chroma_G->setObjectName(QStringLiteral("horizontalSlider_chroma_G"));
        horizontalSlider_chroma_G->setGeometry(QRect(26, 48, 102, 16));
        horizontalSlider_chroma_G->setMaximum(255);
        horizontalSlider_chroma_G->setOrientation(Qt::Horizontal);
        horizontalSlider_chroma_B = new QSlider(groupBox_3);
        horizontalSlider_chroma_B->setObjectName(QStringLiteral("horizontalSlider_chroma_B"));
        horizontalSlider_chroma_B->setGeometry(QRect(26, 76, 102, 16));
        horizontalSlider_chroma_B->setMaximum(255);
        horizontalSlider_chroma_B->setOrientation(Qt::Horizontal);
        label_45 = new QLabel(groupBox_3);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(8, 72, 16, 20));
        spinBox_chroma_R = new QSpinBox(groupBox_3);
        spinBox_chroma_R->setObjectName(QStringLiteral("spinBox_chroma_R"));
        spinBox_chroma_R->setGeometry(QRect(130, 16, 46, 22));
        spinBox_chroma_R->setMaximum(255);
        spinBox_chroma_G = new QSpinBox(groupBox_3);
        spinBox_chroma_G->setObjectName(QStringLiteral("spinBox_chroma_G"));
        spinBox_chroma_G->setGeometry(QRect(130, 44, 46, 22));
        spinBox_chroma_G->setMaximum(255);
        spinBox_chroma_B = new QSpinBox(groupBox_3);
        spinBox_chroma_B->setObjectName(QStringLiteral("spinBox_chroma_B"));
        spinBox_chroma_B->setGeometry(QRect(130, 72, 46, 22));
        spinBox_chroma_B->setMaximum(255);
        spinBox_chroma_RT = new QSpinBox(groupBox_3);
        spinBox_chroma_RT->setObjectName(QStringLiteral("spinBox_chroma_RT"));
        spinBox_chroma_RT->setGeometry(QRect(374, 16, 46, 22));
        spinBox_chroma_RT->setMaximum(255);
        label_46 = new QLabel(groupBox_3);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(252, 44, 16, 20));
        horizontalSlider_chroma_GT = new QSlider(groupBox_3);
        horizontalSlider_chroma_GT->setObjectName(QStringLiteral("horizontalSlider_chroma_GT"));
        horizontalSlider_chroma_GT->setGeometry(QRect(270, 48, 102, 16));
        horizontalSlider_chroma_GT->setMaximum(255);
        horizontalSlider_chroma_GT->setOrientation(Qt::Horizontal);
        label_47 = new QLabel(groupBox_3);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(252, 16, 16, 20));
        horizontalSlider_chroma_RT = new QSlider(groupBox_3);
        horizontalSlider_chroma_RT->setObjectName(QStringLiteral("horizontalSlider_chroma_RT"));
        horizontalSlider_chroma_RT->setGeometry(QRect(270, 20, 102, 16));
        horizontalSlider_chroma_RT->setMaximum(255);
        horizontalSlider_chroma_RT->setOrientation(Qt::Horizontal);
        label_48 = new QLabel(groupBox_3);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(252, 72, 16, 20));
        horizontalSlider_chroma_BT = new QSlider(groupBox_3);
        horizontalSlider_chroma_BT->setObjectName(QStringLiteral("horizontalSlider_chroma_BT"));
        horizontalSlider_chroma_BT->setGeometry(QRect(270, 76, 102, 16));
        horizontalSlider_chroma_BT->setMaximum(255);
        horizontalSlider_chroma_BT->setOrientation(Qt::Horizontal);
        spinBox_chroma_BT = new QSpinBox(groupBox_3);
        spinBox_chroma_BT->setObjectName(QStringLiteral("spinBox_chroma_BT"));
        spinBox_chroma_BT->setGeometry(QRect(374, 72, 46, 22));
        spinBox_chroma_BT->setMaximum(255);
        spinBox_chroma_GT = new QSpinBox(groupBox_3);
        spinBox_chroma_GT->setObjectName(QStringLiteral("spinBox_chroma_GT"));
        spinBox_chroma_GT->setGeometry(QRect(374, 44, 46, 22));
        spinBox_chroma_GT->setMaximum(255);
        button_pick_color = new QPushButton(groupBox_3);
        button_pick_color->setObjectName(QStringLiteral("button_pick_color"));
        button_pick_color->setGeometry(QRect(186, 12, 59, 87));
        QFont font;
        font.setBold(false);
        font.setWeight(50);
        font.setKerning(true);
        button_pick_color->setFont(font);
        button_pick_color->setLayoutDirection(Qt::LeftToRight);
        button_pick_color->setAutoFillBackground(true);
        button_pick_color->setStyleSheet(QStringLiteral(""));
        button_pick_color->setAutoRepeat(false);
        button_pick_color->setAutoDefault(false);
        button_pick_color->setDefault(false);
        button_pick_color->setFlat(false);
        checkBoxChromaEnabled = new QCheckBox(Color);
        checkBoxChromaEnabled->setObjectName(QStringLiteral("checkBoxChromaEnabled"));
        checkBoxChromaEnabled->setGeometry(QRect(6, 110, 101, 18));
        QFont font1;
        font1.setPointSize(9);
        font1.setBold(true);
        font1.setWeight(75);
        checkBoxChromaEnabled->setFont(font1);
        tabWidget->addTab(Color, QString());
        Possition = new QWidget();
        Possition->setObjectName(QStringLiteral("Possition"));
        Position = new QGroupBox(Possition);
        Position->setObjectName(QStringLiteral("Position"));
        Position->setGeometry(QRect(0, 0, 431, 97));
        label = new QLabel(Position);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 16, 41, 20));
        horizontalSlider_X_Pos = new QSlider(Position);
        horizontalSlider_X_Pos->setObjectName(QStringLiteral("horizontalSlider_X_Pos"));
        horizontalSlider_X_Pos->setGeometry(QRect(60, 20, 105, 16));
        horizontalSlider_X_Pos->setMaximum(100);
        horizontalSlider_X_Pos->setOrientation(Qt::Horizontal);
        label_2 = new QLabel(Position);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 46, 51, 20));
        horizontalSlider_Width = new QSlider(Position);
        horizontalSlider_Width->setObjectName(QStringLiteral("horizontalSlider_Width"));
        horizontalSlider_Width->setGeometry(QRect(60, 50, 105, 16));
        horizontalSlider_Width->setMaximum(100);
        horizontalSlider_Width->setOrientation(Qt::Horizontal);
        label_3 = new QLabel(Position);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(220, 16, 41, 20));
        horizontalSlider_Y_Pos = new QSlider(Position);
        horizontalSlider_Y_Pos->setObjectName(QStringLiteral("horizontalSlider_Y_Pos"));
        horizontalSlider_Y_Pos->setGeometry(QRect(274, 20, 105, 16));
        horizontalSlider_Y_Pos->setMaximum(100);
        horizontalSlider_Y_Pos->setOrientation(Qt::Horizontal);
        label_4 = new QLabel(Position);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(220, 46, 51, 20));
        horizontalSlider_Height = new QSlider(Position);
        horizontalSlider_Height->setObjectName(QStringLiteral("horizontalSlider_Height"));
        horizontalSlider_Height->setGeometry(QRect(274, 50, 105, 16));
        horizontalSlider_Height->setMaximum(100);
        horizontalSlider_Height->setOrientation(Qt::Horizontal);
        spinBox_X_Pos = new QSpinBox(Position);
        spinBox_X_Pos->setObjectName(QStringLiteral("spinBox_X_Pos"));
        spinBox_X_Pos->setGeometry(QRect(167, 16, 45, 22));
        spinBox_X_Pos->setMaximum(100);
        spinBox_Width = new QSpinBox(Position);
        spinBox_Width->setObjectName(QStringLiteral("spinBox_Width"));
        spinBox_Width->setGeometry(QRect(167, 46, 45, 22));
        spinBox_Width->setMaximum(100);
        spinBox_Y_Pos = new QSpinBox(Position);
        spinBox_Y_Pos->setObjectName(QStringLiteral("spinBox_Y_Pos"));
        spinBox_Y_Pos->setGeometry(QRect(381, 16, 45, 22));
        spinBox_Y_Pos->setMaximum(100);
        spinBox_Height = new QSpinBox(Position);
        spinBox_Height->setObjectName(QStringLiteral("spinBox_Height"));
        spinBox_Height->setGeometry(QRect(381, 46, 45, 22));
        spinBox_Height->setMaximum(100);
        checkBox_keepaspect = new QCheckBox(Position);
        checkBox_keepaspect->setObjectName(QStringLiteral("checkBox_keepaspect"));
        checkBox_keepaspect->setGeometry(QRect(10, 72, 127, 18));
        QFont font2;
        font2.setBold(true);
        font2.setWeight(75);
        checkBox_keepaspect->setFont(font2);
        Position_3 = new QGroupBox(Possition);
        Position_3->setObjectName(QStringLiteral("Position_3"));
        Position_3->setGeometry(QRect(0, 100, 431, 97));
        label_9 = new QLabel(Position_3);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 16, 47, 20));
        horizontalSlider_X_Angle = new QSlider(Position_3);
        horizontalSlider_X_Angle->setObjectName(QStringLiteral("horizontalSlider_X_Angle"));
        horizontalSlider_X_Angle->setGeometry(QRect(60, 20, 105, 16));
        horizontalSlider_X_Angle->setMaximum(360);
        horizontalSlider_X_Angle->setOrientation(Qt::Horizontal);
        label_10 = new QLabel(Position_3);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 46, 51, 20));
        horizontalSlider_Y_Angle = new QSlider(Position_3);
        horizontalSlider_Y_Angle->setObjectName(QStringLiteral("horizontalSlider_Y_Angle"));
        horizontalSlider_Y_Angle->setGeometry(QRect(60, 50, 105, 16));
        horizontalSlider_Y_Angle->setMaximum(360);
        horizontalSlider_Y_Angle->setOrientation(Qt::Horizontal);
        label_11 = new QLabel(Position_3);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(220, 16, 49, 20));
        horizontalSlider_Z_Angle = new QSlider(Position_3);
        horizontalSlider_Z_Angle->setObjectName(QStringLiteral("horizontalSlider_Z_Angle"));
        horizontalSlider_Z_Angle->setGeometry(QRect(274, 20, 105, 16));
        horizontalSlider_Z_Angle->setMaximum(360);
        horizontalSlider_Z_Angle->setOrientation(Qt::Horizontal);
        label_12 = new QLabel(Position_3);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(220, 46, 51, 20));
        horizontalSlider_Animate = new QSlider(Position_3);
        horizontalSlider_Animate->setObjectName(QStringLiteral("horizontalSlider_Animate"));
        horizontalSlider_Animate->setGeometry(QRect(274, 50, 105, 16));
        horizontalSlider_Animate->setMaximum(100);
        horizontalSlider_Animate->setOrientation(Qt::Horizontal);
        spinBox_X_Angle = new QSpinBox(Position_3);
        spinBox_X_Angle->setObjectName(QStringLiteral("spinBox_X_Angle"));
        spinBox_X_Angle->setGeometry(QRect(167, 16, 45, 22));
        spinBox_X_Angle->setMaximum(360);
        spinBox_Y_Angle = new QSpinBox(Position_3);
        spinBox_Y_Angle->setObjectName(QStringLiteral("spinBox_Y_Angle"));
        spinBox_Y_Angle->setGeometry(QRect(167, 46, 45, 22));
        spinBox_Y_Angle->setMaximum(360);
        spinBox_Animate = new QSpinBox(Position_3);
        spinBox_Animate->setObjectName(QStringLiteral("spinBox_Animate"));
        spinBox_Animate->setGeometry(QRect(381, 46, 45, 22));
        spinBox_Animate->setMaximum(100);
        spinBox_Z_Angle = new QSpinBox(Position_3);
        spinBox_Z_Angle->setObjectName(QStringLiteral("spinBox_Z_Angle"));
        spinBox_Z_Angle->setGeometry(QRect(381, 16, 45, 22));
        spinBox_Z_Angle->setMaximum(360);
        Position_4 = new QGroupBox(Possition);
        Position_4->setObjectName(QStringLiteral("Position_4"));
        Position_4->setGeometry(QRect(0, 200, 431, 97));
        label_13 = new QLabel(Position_4);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 16, 47, 20));
        horizontalSlider_Clip_Top = new QSlider(Position_4);
        horizontalSlider_Clip_Top->setObjectName(QStringLiteral("horizontalSlider_Clip_Top"));
        horizontalSlider_Clip_Top->setGeometry(QRect(60, 20, 105, 16));
        horizontalSlider_Clip_Top->setMaximum(100);
        horizontalSlider_Clip_Top->setOrientation(Qt::Horizontal);
        label_14 = new QLabel(Position_4);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(10, 46, 51, 20));
        horizontalSlider_Clip_Left = new QSlider(Position_4);
        horizontalSlider_Clip_Left->setObjectName(QStringLiteral("horizontalSlider_Clip_Left"));
        horizontalSlider_Clip_Left->setGeometry(QRect(60, 50, 105, 16));
        horizontalSlider_Clip_Left->setMaximum(100);
        horizontalSlider_Clip_Left->setOrientation(Qt::Horizontal);
        label_15 = new QLabel(Position_4);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(220, 16, 49, 20));
        horizontalSlider_Clip_Bottom = new QSlider(Position_4);
        horizontalSlider_Clip_Bottom->setObjectName(QStringLiteral("horizontalSlider_Clip_Bottom"));
        horizontalSlider_Clip_Bottom->setGeometry(QRect(274, 20, 105, 16));
        horizontalSlider_Clip_Bottom->setMaximum(100);
        horizontalSlider_Clip_Bottom->setOrientation(Qt::Horizontal);
        label_16 = new QLabel(Position_4);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(220, 46, 51, 20));
        horizontalSlider_Clip_Right = new QSlider(Position_4);
        horizontalSlider_Clip_Right->setObjectName(QStringLiteral("horizontalSlider_Clip_Right"));
        horizontalSlider_Clip_Right->setGeometry(QRect(274, 50, 105, 16));
        horizontalSlider_Clip_Right->setMaximum(100);
        horizontalSlider_Clip_Right->setOrientation(Qt::Horizontal);
        spinBox_Clip_Top = new QSpinBox(Position_4);
        spinBox_Clip_Top->setObjectName(QStringLiteral("spinBox_Clip_Top"));
        spinBox_Clip_Top->setGeometry(QRect(167, 16, 45, 22));
        spinBox_Clip_Top->setMaximum(100);
        spinBox_Clip_Left = new QSpinBox(Position_4);
        spinBox_Clip_Left->setObjectName(QStringLiteral("spinBox_Clip_Left"));
        spinBox_Clip_Left->setGeometry(QRect(167, 46, 45, 22));
        spinBox_Clip_Left->setMaximum(100);
        spinBox_Clip_Bottom = new QSpinBox(Position_4);
        spinBox_Clip_Bottom->setObjectName(QStringLiteral("spinBox_Clip_Bottom"));
        spinBox_Clip_Bottom->setGeometry(QRect(381, 16, 45, 22));
        spinBox_Clip_Bottom->setMaximum(100);
        spinBox_Clip_Right = new QSpinBox(Position_4);
        spinBox_Clip_Right->setObjectName(QStringLiteral("spinBox_Clip_Right"));
        spinBox_Clip_Right->setGeometry(QRect(381, 46, 45, 22));
        spinBox_Clip_Right->setMaximum(100);
        tabWidget->addTab(Possition, QString());
        Filters = new QWidget();
        Filters->setObjectName(QStringLiteral("Filters"));
        tabWidget->addTab(Filters, QString());

        retranslateUi(SurfaceSetting);
        QObject::connect(horizontalSlider_chroma_R, SIGNAL(valueChanged(int)), spinBox_chroma_R, SLOT(setValue(int)));
        QObject::connect(spinBox_chroma_R, SIGNAL(valueChanged(int)), horizontalSlider_chroma_R, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_chroma_G, SIGNAL(valueChanged(int)), spinBox_chroma_G, SLOT(setValue(int)));
        QObject::connect(spinBox_chroma_G, SIGNAL(valueChanged(int)), horizontalSlider_chroma_G, SLOT(setValue(int)));
        QObject::connect(spinBox_chroma_B, SIGNAL(valueChanged(int)), horizontalSlider_chroma_B, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_chroma_B, SIGNAL(valueChanged(int)), spinBox_chroma_B, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_Brightness, SIGNAL(valueChanged(int)), spinBox_Brightness, SLOT(setValue(int)));
        QObject::connect(spinBox_Brightness, SIGNAL(valueChanged(int)), horizontalSlider_Brightness, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_Contrast, SIGNAL(valueChanged(int)), spinBox_Contrast, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_Transparency, SIGNAL(valueChanged(int)), spinBox_Transparency, SLOT(setValue(int)));
        QObject::connect(spinBox_Transparency, SIGNAL(valueChanged(int)), horizontalSlider_Transparency, SLOT(setValue(int)));
        QObject::connect(spinBox_Contrast, SIGNAL(valueChanged(int)), horizontalSlider_Contrast, SLOT(setValue(int)));
        QObject::connect(spinBox_R, SIGNAL(valueChanged(int)), horizontalSlider_R, SLOT(setValue(int)));
        QObject::connect(spinBox_G, SIGNAL(valueChanged(int)), horizontalSlider_G, SLOT(setValue(int)));
        QObject::connect(spinBox_B, SIGNAL(valueChanged(int)), horizontalSlider_B, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_B, SIGNAL(valueChanged(int)), spinBox_B, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_G, SIGNAL(valueChanged(int)), spinBox_G, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_R, SIGNAL(valueChanged(int)), spinBox_R, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_X_Pos, SIGNAL(valueChanged(int)), spinBox_X_Pos, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_Y_Pos, SIGNAL(valueChanged(int)), spinBox_Y_Pos, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_Height, SIGNAL(valueChanged(int)), spinBox_Height, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_Width, SIGNAL(valueChanged(int)), spinBox_Width, SLOT(setValue(int)));
        QObject::connect(spinBox_X_Pos, SIGNAL(valueChanged(int)), horizontalSlider_X_Pos, SLOT(setValue(int)));
        QObject::connect(spinBox_Y_Pos, SIGNAL(valueChanged(int)), horizontalSlider_Y_Pos, SLOT(setValue(int)));
        QObject::connect(spinBox_Height, SIGNAL(valueChanged(int)), horizontalSlider_Height, SLOT(setValue(int)));
        QObject::connect(spinBox_Width, SIGNAL(valueChanged(int)), horizontalSlider_Width, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_X_Angle, SIGNAL(valueChanged(int)), spinBox_X_Angle, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_Y_Angle, SIGNAL(valueChanged(int)), spinBox_Y_Angle, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_Z_Angle, SIGNAL(valueChanged(int)), spinBox_Z_Angle, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_Animate, SIGNAL(valueChanged(int)), spinBox_Animate, SLOT(setValue(int)));
        QObject::connect(spinBox_X_Angle, SIGNAL(valueChanged(int)), horizontalSlider_X_Angle, SLOT(setValue(int)));
        QObject::connect(spinBox_Y_Angle, SIGNAL(valueChanged(int)), horizontalSlider_Y_Angle, SLOT(setValue(int)));
        QObject::connect(spinBox_Z_Angle, SIGNAL(valueChanged(int)), horizontalSlider_Z_Angle, SLOT(setValue(int)));
        QObject::connect(spinBox_Animate, SIGNAL(valueChanged(int)), horizontalSlider_Animate, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_Clip_Top, SIGNAL(valueChanged(int)), spinBox_Clip_Top, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_Clip_Bottom, SIGNAL(valueChanged(int)), spinBox_Clip_Bottom, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_Clip_Left, SIGNAL(valueChanged(int)), spinBox_Clip_Left, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_Clip_Right, SIGNAL(valueChanged(int)), spinBox_Clip_Right, SLOT(setValue(int)));
        QObject::connect(spinBox_Clip_Bottom, SIGNAL(valueChanged(int)), horizontalSlider_Clip_Bottom, SLOT(setValue(int)));
        QObject::connect(spinBox_Clip_Left, SIGNAL(valueChanged(int)), horizontalSlider_Clip_Left, SLOT(setValue(int)));
        QObject::connect(spinBox_Clip_Right, SIGNAL(valueChanged(int)), horizontalSlider_Clip_Right, SLOT(setValue(int)));
        QObject::connect(spinBox_Clip_Top, SIGNAL(valueChanged(int)), horizontalSlider_Clip_Top, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_chroma_RT, SIGNAL(valueChanged(int)), spinBox_chroma_RT, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_chroma_BT, SIGNAL(valueChanged(int)), spinBox_chroma_BT, SLOT(setValue(int)));
        QObject::connect(horizontalSlider_chroma_GT, SIGNAL(valueChanged(int)), spinBox_chroma_GT, SLOT(setValue(int)));
        QObject::connect(spinBox_chroma_RT, SIGNAL(valueChanged(int)), horizontalSlider_chroma_RT, SLOT(setValue(int)));
        QObject::connect(spinBox_chroma_BT, SIGNAL(valueChanged(int)), horizontalSlider_chroma_BT, SLOT(setValue(int)));
        QObject::connect(spinBox_chroma_GT, SIGNAL(valueChanged(int)), horizontalSlider_chroma_GT, SLOT(setValue(int)));

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(SurfaceSetting);
    } // setupUi

    void retranslateUi(QWidget *SurfaceSetting)
    {
        SurfaceSetting->setWindowTitle(QApplication::translate("SurfaceSetting", "Surface settings", 0));
        groupBox->setTitle(QApplication::translate("SurfaceSetting", "Picture", 0));
        label_5->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Brightness</span></p></body></html>", 0));
        label_6->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Contrast</span></p></body></html>", 0));
        label_7->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#000000;\">Transparency</span></p></body></html>", 0));
        label_31->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">R</span></p></body></html>", 0));
        label_32->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">G</span></p></body></html>", 0));
        label_33->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">B</span></p></body></html>", 0));
        groupBox_3->setTitle(QApplication::translate("SurfaceSetting", "Chroma", 0));
        label_43->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">R</span></p></body></html>", 0));
        label_44->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">G</span></p></body></html>", 0));
        label_45->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">B</span></p></body></html>", 0));
        label_46->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">GT</span></p></body></html>", 0));
        label_47->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">RT</span></p></body></html>", 0));
        label_48->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">BT</span></p></body></html>", 0));
        button_pick_color->setText(QApplication::translate("SurfaceSetting", "Pick", 0));
        checkBoxChromaEnabled->setText(QApplication::translate("SurfaceSetting", "Chroma key", 0));
        tabWidget->setTabText(tabWidget->indexOf(Color), QApplication::translate("SurfaceSetting", "Color", 0));
        Position->setTitle(QApplication::translate("SurfaceSetting", "Position", 0));
        label->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#000000;\">X pos</span></p></body></html>", 0));
        label_2->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#000000;\">Width</span></p></body></html>", 0));
        label_3->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#000000;\">Y pos</span></p></body></html>", 0));
        label_4->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#000000;\">Height</span></p></body></html>", 0));
        checkBox_keepaspect->setText(QApplication::translate("SurfaceSetting", "Keep aspect ratio", 0));
        Position_3->setTitle(QApplication::translate("SurfaceSetting", "3D", 0));
        label_9->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#000000;\">X angle</span></p></body></html>", 0));
        label_10->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#000000;\">Y angle</span></p></body></html>", 0));
        label_11->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Z angle</span></p></body></html>", 0));
        label_12->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#000000;\">Reserved</span></p></body></html>", 0));
        Position_4->setTitle(QApplication::translate("SurfaceSetting", "Clip", 0));
        label_13->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#000000;\">Top</span></p></body></html>", 0));
        label_14->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#000000;\">Left</span></p></body></html>", 0));
        label_15->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Bottom</span></p></body></html>", 0));
        label_16->setText(QApplication::translate("SurfaceSetting", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#000000;\">Right</span></p></body></html>", 0));
        tabWidget->setTabText(tabWidget->indexOf(Possition), QApplication::translate("SurfaceSetting", "Possition", 0));
        tabWidget->setTabText(tabWidget->indexOf(Filters), QApplication::translate("SurfaceSetting", "Filters", 0));
    } // retranslateUi

};

namespace Ui {
    class SurfaceSetting: public Ui_SurfaceSetting {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MQS_SURFACE_SETTINGS_H
